[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
  
  "@DSC/=src/DecentralisedStableCoin/",
  "@DSCTest/=test/DecentralisedStableCoin/",
  "@DSCScript/=script/DecentralisedStableCoin/",

  "@Raffle/=src/Raffle/",
  "@RaffleTest/=test/Raffle/",
  "@RaffleScript/=script/Raffle/",

  '@solmate/=lib/solmate',
  '@devops/=lib/foundry-devops/',
  
  "@mock/=test/mock/",
  "@library/=src/library/"

]

[invariant]
runs = 256
depth = 128
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

